from dotenv import load_dotenv
import os


load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
LINKEDIN_CLIENT_SECRET = os.getenv("LINKEDIN_CLIENT_SECRET")
LINKEDIN_CLIENT_ID = os.getenv("LINKEDIN_CLIENT_ID")
GENAI_BOT_TOKEN = os.getenv("GENAI_BOT_TOKEN")
GENAI_CHANNEL_USERNAME = os.getenv("GENAI_CHANNEL_USERNAME")
POSTIN_LINKED_IN_CLIENT_ID = os.getenv("POSTIN_LINKED_IN_CLIENT_ID")
POSTIN_LINKED_IN_CLIENT_SECRET = os.getenv("POSTIN_LINKED_IN_CLIENT_SECRET")
POSTIN_ACCESS_TOKEN = os.getenv("POSTIN_ACCESS_TOKEN")
POSTIN_KALISH_AYISH_URN = os.getenv("POSTIN_KALISH_AYISH_URN")

POSTIST_AUTH_CODE = os.getenv("POSTIST_AUTH_CODE")
POSTIST_ACCESS_TOKEN = os.getenv("POSTIST_ACCESS_TOKEN")
POSTIST_REFRESH_TOKEN = os.getenv("POSTIST_REFRESH_TOKEN")
STARTIST_PAGE_ID = os.getenv("STARTIST_PAGE_ID")
